### ISSUE TITLE
how do you run it??

### ISSUE THREAD

**Issue by donnerkebab1730** [Textovortex/AdventButWrong#1]
how do you run it (and could you add it to the readme)

**Comment by leha-code** [comment]
Alright, you install the DEB file provided [here](
https://textovortex.github.io/AdventButWrong/lastest.deb) or in the
latest release.

**Comment by leha-code** [comment]
I'll add it to readme soon too, for people who don't use Linux or Termux.

**Comment by donnerkebab1730** [comment]
after downloading the file it just vannished, am i doing it wrong?

**Comment by leha-code** [comment]
Screenshot

sent from not an computer

**Comment by donnerkebab1730** [comment]
nvm beiop fixed it

**Comment by donnerkebab1730** [comment]
for anybody that has the same issue and is looking around 

 
do  git clone https://github.com/Textovortex/AdventButWrong.git


then go to your home file directory


open adventbutwrong

go to the folder titled opt and click on main.py and open with thonny

**Comment by donnerkebab1730** [comment]
closing the issue now...
